controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

qr_code:
    path: '/qr-code'
    controller: App\Controller\QrCodeController::generateQrCode